[defaults]
format = "{time}\n"

[[sessions]]
id = "work"
name = "Work"
duration = "1h"
command = "notify-send 'Work Done!' && paplay ~/scripts/notification.wav && /home/zach/.local/share/pipx/venvs/telegram-send/bin/telegram-send 'Work Done!'"

[[sessions]]
id = "rest"
name = "Rest"
duration = "10m"
command = "notify-send 'Rest Done!' && paplay ~/scripts/notification.wav && /home/zach/.local/share/pipx/venvs/telegram-send/bin/telegram-send 'Rest Done!'"

# [[sessions]]
# id = "hardwork"
# name = "Work, but harder"
# duration = "1h 45m"
# command = "notify-send 'Hard Work Done!' && paplay ~/scripts/notification.wav && /home/zach/.local/share/pipx/venvs/telegram-send/bin/telegram-send 'Hard Work Done!'"
